#!/usr/bin/env bash
# nginx installation listen to curl 80
apt-get update
apt-get -y install curl
rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
