#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration Hi
count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 8 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
