#!/usr/bin/env bash
#Script that loops form 1 -10
count=1

while [ $count -lt 11 ]
do
	if [ $count = 4 ]
	then
		echo "bad luck"
	elif [ $count = 8 ]
	then
		echo "good luck"
	else
		echo "Best Schoool"
	fi
	(( count++ ))
done
