#!/usr/bin/env bash
#Script that loops form 1 -10
count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best Schoool"
	fi
	(( count++ ))
done
