#!/usr/bin/env bash
#Script that loops form 1 -10
count=0

while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best Schoool"
	fi
	(( counter++ ))
done
